import { SurveyData } from '@/types/survey';

export const generatePDFReport = async (surveyData: SurveyData): Promise<void> => {
  const { survey, rooms, items } = surveyData;
  
  // Create a printable HTML document
  const reportWindow = window.open('', '_blank');
  if (!reportWindow) {
    throw new Error('Could not open print window');
  }
  
  const itemsByRoom = rooms.map(room => ({
    room,
    items: items.filter(item => item.roomId === room.roomId)
  }));
  
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>AX4 Asbestos Survey Report - ${survey.jobId}</title>
      <style>
        body { 
          font-family: Arial, sans-serif; 
          margin: 20px; 
          line-height: 1.4; 
          color: #333;
        }
        .header { 
          text-align: center; 
          border-bottom: 2px solid #0066cc; 
          padding-bottom: 20px; 
          margin-bottom: 30px; 
        }
        .header h1 { 
          color: #0066cc; 
          margin: 0; 
          font-size: 24px; 
        }
        .header h2 { 
          color: #666; 
          margin: 5px 0; 
          font-weight: normal; 
        }
        .survey-info { 
          background: #f8f9fa; 
          padding: 15px; 
          border-radius: 5px; 
          margin-bottom: 20px; 
        }
        .survey-info table { 
          width: 100%; 
          border-collapse: collapse; 
        }
        .survey-info td { 
          padding: 8px; 
          border: none; 
        }
        .survey-info td:first-child { 
          font-weight: bold; 
          width: 150px; 
        }
        .room-section { 
          margin: 30px 0; 
          page-break-inside: avoid; 
        }
        .room-title { 
          background: #0066cc; 
          color: white; 
          padding: 10px; 
          margin: 0; 
          font-size: 18px; 
        }
        .items-table { 
          width: 100%; 
          border-collapse: collapse; 
          margin-top: 0; 
        }
        .items-table th, .items-table td { 
          border: 1px solid #ddd; 
          padding: 8px; 
          text-align: left; 
          vertical-align: top; 
        }
        .items-table th { 
          background: #f1f1f1; 
          font-weight: bold; 
        }
        .risk-low { color: #28a745; font-weight: bold; }
        .risk-medium { color: #ffc107; font-weight: bold; }
        .risk-high { color: #dc3545; font-weight: bold; }
        .footer { 
          margin-top: 40px; 
          padding-top: 20px; 
          border-top: 1px solid #ddd; 
          text-align: center; 
          color: #666; 
          font-size: 12px; 
        }
        @media print {
          body { margin: 0; }
          .room-section { page-break-before: auto; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>AX4 Environmental Services</h1>
        <h2>Asbestos Survey Report</h2>
      </div>
      
      <div class="survey-info">
        <table>
          <tr><td>Job ID:</td><td>${survey.jobId}</td></tr>
          <tr><td>Site Name:</td><td>${survey.siteName}</td></tr>
          <tr><td>Survey Type:</td><td>${survey.surveyType}</td></tr>
          <tr><td>Surveyor:</td><td>${survey.surveyor}</td></tr>
          <tr><td>Date:</td><td>${new Date(survey.date).toLocaleDateString()}</td></tr>
          ${survey.gpsCoordinates ? `<tr><td>GPS Coordinates:</td><td>${survey.gpsCoordinates}</td></tr>` : ''}
        </table>
      </div>
      
      ${itemsByRoom.map(({ room, items }) => `
        <div class="room-section">
          <h3 class="room-title">${room.roomName}</h3>
          ${items.length > 0 ? `
            <table class="items-table">
              <thead>
                <tr>
                  <th>Ref #</th>
                  <th>Location</th>
                  <th>Item Description</th>
                  <th>Material Type</th>
                  <th>Risk Level</th>
                  <th>Recommendation</th>
                  <th>Notes</th>
                </tr>
              </thead>
              <tbody>
                ${items.map(item => `
                  <tr>
                    <td>${item.referenceNumber}</td>
                    <td>${item.locationDescription}</td>
                    <td>${item.itemDescription}</td>
                    <td>${item.materialType}</td>
                    <td class="risk-${item.riskLevel.toLowerCase()}">${item.riskLevel}</td>
                    <td>${item.recommendation}</td>
                    <td>${item.notes || '-'}</td>
                  </tr>
                `).join('')}
              </tbody>
            </table>
          ` : '<p>No items recorded for this area.</p>'}
        </div>
      `).join('')}
      
      <div class="footer">
        <p><strong>Compliance:</strong> SA WHS Regulations 2012, AS 1319–1994</p>
        <p>Generated by AX4 Asbestos Survey Tool | Contact: admin@ax4.com.au</p>
        <p>Report generated on ${new Date().toLocaleString()}</p>
      </div>
    </body>
    </html>
  `;
  
  reportWindow.document.write(html);
  reportWindow.document.close();
  
  // Auto-trigger print dialog
  setTimeout(() => {
    reportWindow.print();
  }, 500);
};